services:
  wikilite:
    image: wikilite
    container_name: wikilite
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "35248:35248"
    volumes:
      - wikilite-data:/app/data
    restart: unless-stopped

volumes:
  wikilite-data:

